# base images
FROM python:3.9

# Install pip dependancy.
WORKDIR /code

COPY requirements.txt /requirements.txt

# Install pip dependancy.
RUN pip install -r /requirements.txt

# copy whole directory inside /code working directory.
COPY . /code# This command execute at the time when conatiner start.

# This command execute at the time when conatiner start.
CMD ["python3", "app.py"]